# run: conda env create -f requirements.yml
name: monitor
channels:
  - defaults
dependencies:
  - python=3.8.8
  - pip
  - pip:
      - wehcatpy
      - requests
      - beautifulsoup4
      - schedule